### ISSUE TITLE
How to execute some code in background

### ISSUE THREAD

**Issue by tulioccalazans** [markszente/background_refresh_status#1]
This package get the status of "Background App Refresh", right?

How can I execute some code in background?
Is it possible through this package OR some other package OR is it necessary to create native codes?

**Comment by markszente** [comment]
This package allows you to determine whether your app can refresh content when running in the background

You can try the [background_fetch](https://pub.dev/packages/background_fetch) package to perform some logic in the background. However, background mode on iOS is pretty limited.
